### ISSUE TITLE
[bug?] Ubuntu 14.04 wrong dependencies of php-xml / php5-xml

### ISSUE THREAD

**Issue by beinbliss** [phoronix-test-suite/phoronix-test-suite#151] opened 2017-01-13 19:24 UTC
Have downloaded phoronix-test-suite_6.8.0_all.deb from the official site: http://www.phoronix-test-suite.com/?k=downloads phoronix-test-suite_6.8.0_all.deb package.

And it does install with errors:
**~# dpkg -i phoronix-test-suite_6.8.0_all.deb**
Selecting previously unselected package phoronix-test-suite.
(Reading database ... 64981 files and directories currently installed.)
Preparing to unpack phoronix-test-suite_6.8.0_all.deb ...
Unpacking phoronix-test-suite (6.8.0) ...
dpkg: dependency problems prevent configuration of phoronix-test-suite:
 phoronix-test-suite depends on php5-xml | php-xml; however:
  Package php5-xml is not installed.
  Package php-xml is not installed.
dpkg: error processing package phoronix-test-suite (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 phoronix-test-suite

**It depends on non-existing package, since XML module is in-built in php since like ages ago.**

**~# apt-get install php-xml php5-xml**
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php5-xml is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php-xml is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php-xml' has no installation candidate
E: Package 'php5-xml' has no installation candidate

**~# php -m|grep xml**
libxml
xml
xmlreader
xmlwriter

**# cat /etc/issue**
Ubuntu 14.04.5 LTS \n \l

**Comment by michaellarabel** [comment] 2017-01-13 19:32
The issue is fixed by https://github.com/phoronix-test-suite/phoronix-test-suite/commit/ee17c558b54c95cfc8822c01d828cfe4bd190f39 next time the deb packages are generated. On older Ubuntu releases, only php5-cli is needed. It's with Ubuntu 16.04 and newer where the XML package was separated as part of their PHP7 transition where they now have php-cli and php-xml.

**Closed by michaellarabel** 2017-01-13 19:32 UTC
