### ISSUE TITLE
Where can I found why these cases fail?

### ISSUE THREAD

**Issue by HaHoYou** [phoronix-test-suite/phoronix-test-suite#300] opened 2018-10-22 06:25 UTC
Some case fails without error message: 
![fail](https://user-images.githubusercontent.com/34019119/47279540-5fc8ab80-d604-11e8-8a05-ff62da11f0ad.png)
And there is no this case error message in the log folder: ~\.phoronix-test-suite\test\results\df\
![log](https://user-images.githubusercontent.com/34019119/47279542-60614200-d604-11e8-9ecc-f3a9b506bd90.jpg)
Where can I found why these cases fail?

**Comment by michaellarabel** [comment] 2018-10-22 17:55
This looks to be a duplicate of the other ticket, presumably due to the GitHub issues this morning, so closing the duplicate. But as mentioned in the other thread, phoronix-test-suite debug-run and looking in ~/.phoronix-test-suite/installed-tests/ should be helpful.

**Closed by michaellarabel** 2018-10-22 17:55 UTC
