### ISSUE TITLE
stress-run on FreeBSD pegs one core only

### ISSUE THREAD

**Issue by nagisa** [phoronix-test-suite/phoronix-test-suite#192] opened 2017-08-05 16:19 UTC
Installed the git version of the PTS (tried also 7.2 download from the website) to try reproducing the ryzen issue on freebsd.

```
phoronix-test-suite install pts/build-php pts/build-apache pts/build-imagemagick
PTS_CONCURRENT_TEST_RUNS=3 TOTAL_LOOP_TIME=10 phoronix-test-suite stress-run build-php buld-apache build-imagemagick
```

and observed the php process pegging a single core, instead of expected stress tests running.

Tried with both php56 and php71.

**Comment by michaellarabel** [comment] 2017-08-05 16:21
Can you post the output of `phoronix-test-suite php-conf` ? Mainly interested to know if you have the PCNTL support present. The PCNTL extension is needed for being able to handle multi benchmarking threads simultaneously.

**Comment by nagisa** [comment] 2017-08-05 16:24
```
PHP:             5.6.31
PHP VERSION ID:  50631
PHP BINARY:      php

MAIN CAPABILITY CHECK: 
PRESENT - DOM       The Document Object Model is required for XML operations.
PRESENT - ZIP       ZIP support is required for file compression.
PRESENT - JSON      JSON support is required for OpenBenchmarking.org.
PRESENT - SimpleXML SimpleXML is required for XML operations.
MISSING - OpenSSL   OpenSSL support is recommended to support HTTPS traffic.
MISSING - GD        The GD library is recommended for improved graph rendering.
MISSING - Zlib      The Zlib extension can be used for greater file compression.
MISSING - Bzip2     The bzcompress/bzip2 support can be used for greater file compression.
MISSING - SQLite3   SQLite3 is required when running a Phoromatic server.
PRESENT - PCNTL     PCNTL is highly recommended as it is required by some tests.
PRESENT - POSIX     POSIX support is highly recommended.
MISSING - CURL      CURL is recommended for an enhanced download experience.
MISSING - Sockets   Sockets is needed when running the Phoromatic Server.

OPTIONAL FUNCTION CHECKS: 
cli_set_process_title     PRESENT
ctype_alnum               MISSING
ctype_digit               MISSING
curl_init                 MISSING
filter_var                MISSING
finfo_open                MISSING
gzcompress                MISSING
gzdeflate                 MISSING
gzinflate                 MISSING
hash_file                 MISSING
imageantialias            MISSING
imagecreatefromgif        MISSING
imagecreatefrompng        MISSING
imagecreatefromstring     MISSING
imagepng                  MISSING
imagettftext              MISSING
json_decode               PRESENT
pcntl_fork                PRESENT
pcntl_signal              PRESENT
posix_getpid              PRESENT
posix_getpwuid            PRESENT
posix_getuid              PRESENT
posix_isatty              PRESENT
posix_kill                PRESENT
posix_setsid              PRESENT
preg_replace              PRESENT
simplexml_load_string     PRESENT
socket_create_listen      MISSING
sqlite_escape_string      MISSING
ssh2_connect              MISSING
stream_context_set_params PRESENT
timezone_name_from_abbr   PRESENT
zip_open                  PRESENT
```

**Comment by nagisa** [comment] 2017-08-05 16:24
Note that looking at the top output it seems like it just infinite-loops in php itself or something, rather than running the tests.

**Comment by michaellarabel** [comment] 2018-02-06 19:54
@nagisa are you still able to reproduce this on PTS GIt? I've tried several times since on FreeBSD and has worked for me with the configurations I have tried.

**Comment by michaellarabel** [comment] 2018-05-30 21:35
I still have been unable to reproduce this issue. My latest testing of PTS Git on latest FreeBSD/TrueOS has been working fine, so closing for now unless anyone is able to see this single core behavior illustrated on PTS Git.

**Closed by michaellarabel** 2018-05-30 21:35 UTC
