### ISSUE TITLE
3 issues with Mad Max 

### ISSUE THREAD

**Issue by jiansan** [phoronix-test-suite/phoronix-test-suite#228] opened 2017-12-20 19:43 UTC
I am using Ubuntu 16.04.3 plus Kernel 4.15rc2 on an AMD RX 480.

1. My monitor supports 4K resolution and in-game settings does show all possible resolutions. In PTS, maximum resolution listed is 1920x1080. Another problem is some resolution listed are not in the in-game setting. For example, there is 1280x800 listed but the closest in-game setting is 1280x720. The actual tested setting is 1280x720 though.
2. In-game preset graphics settings are Normal/High/Very High. In PTS, the listed options are Low/Default/High.
3. This is the most severe issue in my opinion. No matter which preset graphics setting I choose (Low/Default/High), PTS doesn't apply it successfully in the end. The graphics setting actually comes from the last in-game setting. You can tell from the performance result XML files.

This is my first time evaluate PTS and I am not that familiar with Git. Hopefully I submitted the issue in the right way.

**Comment by michaellarabel** [comment] 2018-01-08 18:46
1. This sounds like some odd combination of GPU/monitor issue I have yet to be able to reproduce on my end. The modes exposed by PTS are what in turn is exposed via the GPU driver/monitor for the system but not provided by the game itself.

2. The labels are based upon their respective setting values communicated by Feral for the values being tested by the benchmark.

3. In a recent madmax test profile update it looks like a change messed the visual quality setting handling. This issue should now be fixed with the pts/madmax-1.2 update. Thanks.

**Closed by michaellarabel** 2018-01-08 18:46 UTC
