### ISSUE TITLE
result-file-to-pdf is broken on Centos 6 / PHP 5.3.3 in v6.2.2

### ISSUE THREAD

**Issue by Elfe** [phoronix-test-suite/phoronix-test-suite#117] opened 2016-04-27 06:16 UTC
When trying to convert a result to PDF I get the error: "PHP Fatal error:  Cannot create references to elements of a temporary array expression in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php on line 237"

php -v
PHP 5.3.3 (cli) (built: Feb  9 2016 10:36:17)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

Phoronix Test Suite v6.2.2 (Gamvik)

CentOS 6.7 with latest updates

phoronix-test-suite result-file-to-pdf 2016-04-25-1757
...
PHP Fatal error:  Cannot create references to elements of a temporary array expression in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php on line 237

**Comment by michaellarabel** [comment] 2016-04-27 11:26
Hi, can you try using the latest PTS Git code? I have been unable to reproduce this issue on my end.

Thanks,
Michael

**Comment by Elfe** [comment] 2016-04-28 09:17
Hi,

I still get this in my test VM with latest git. (different line number)

 "PHP Fatal error:  Cannot create references to elements of a temporary array expression in /root/git/phoronix-test-suite/pts-core/objects/pts_result_file_output.php on line 244"

Thanks

**Comment by michaellarabel** [comment] 2016-04-28 16:00
Ah, now it makes sense from your PHP version and the line number of Git. The issue should be fixed with https://github.com/phoronix-test-suite/phoronix-test-suite/commit/3046b4d707420aef61134dd0424b1baeb8fc718f commit. Thanks. Reopen if any other problems come up.

**Closed by michaellarabel** 2016-04-28 16:00 UTC

**Comment by Elfe** [comment] 2016-04-29 07:03
I don't know if you want to fully support php 5.3 as I get "PHP Fatal error:  Call to undefined function getimagesizefromstring() in /root/phoronix-test-suite/pts-core/objects/FPDF.php on line 1364" as well. This function is only available in >=php5.4

**Comment by Demonsthere** [comment] 2016-11-05 16:51
Hey, I have been trying to convert the results to pdf on debian, however I get a similar error:

 ```bash
vagrant@vm-debian8-local:~/.phoronix-test-suite$ phoronix-test-suite result-file-to-pdf 2016-11-05-1734

[NOTICE] getimagesizefromstring(): Read error! in FPDF:1364
```
My php5-cli version is rather new

```bash
php5-cli:
  Installed: 5.6.27+dfsg-0+deb8u1
  Candidate: 5.6.27+dfsg-0+deb8u1
  Version table:
 *** 5.6.27+dfsg-0+deb8u1 0
        500 http://security.debian.org/ jessie/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     5.6.24+dfsg-0+deb8u1 0
        500 http://ftp.pl.debian.org/debian/ jessie/main amd64 Packages
```

**Comment by AnsgarKlein** [comment] 2016-11-08 15:24
I have the same problem on Ubuntu 16.04 Xenial:
(fresh install, did not install a lot of additional packages)

```
~$ phoronix-test-suite result-file-to-pdf XXX

[8192] Methods with the same name as their class will not be constructors in a future version of PHP; FPDF has a deprecated constructor in FPDF:25

[NOTICE] getimagesizefromstring(): Read error! in FPDF:1364
```




Ubuntu 16.04 does not seem to have php5:
```
~$ dpkg -l | egrep "php.*-cli|phoronix-test-suite|fpdf"
ii  phoronix-test-suite                        6.6.1                                         all          An Automated, Open-Source Testing Framework
ii  php-cli                                    1:7.0+35ubuntu6                               all          command-line interpreter for the PHP scripting language (default)
ii  php-fpdf                                   3:1.7.dfsg-1.1ubuntu1                         all          PHP class to generate PDF files
ii  php7.0-cli                                 7.0.8-0ubuntu0.16.04.3                        amd64        command-line interpreter for the PHP scripting language

```

**Comment by michaellarabel** [comment] 2016-11-08 15:26
@AnsgarKlein  does it work if you have php-gd installed?

**Comment by michaellarabel** [comment] 2016-11-08 15:27
@Demonsthere your error sounds as well like php-gd is msising from your system (or php5-gd if you're still on PHP5). If that fixes it, looks like I just need to improve the error message.

**Comment by AnsgarKlein** [comment] 2016-11-08 15:34
Indeed it does!
I did not see php-gd mentioned as a requirement anywhere.
Sorry for bothering

**Comment by michaellarabel** [comment] 2016-11-08 15:39
Okay, great. Will add a better check to warn the user about php-gd. It's an optional dependency only used in select cases, e.g. result-file-to-pdf.

**Comment by chozian** [comment] 2018-06-27 17:51
@michaellarabel I ran into the same issue as @AnsgarKlein. Installing php-gd in Ubuntu 16.04 with Phoronix 7.8 resolved  it.

**Comment by michaellarabel** [comment] 2018-06-27 18:03
https://github.com/phoronix-test-suite/phoronix-test-suite/commit/acd397cc7e60498c12c5a0bfb5bf2c420b4af792 should now have better detection/reporting of when GD isn't available for graph rendering on the PDF output.
